#!/bin/bash

client_username=git-user

# Check if user exists
id $client_username 1>&2 2>/dev/null
if [ $? -ne 0 ]; then
   echo "ERROR: User $client_username doesn't exist. Exiting..."
   sleep 1
   exit 1
fi

# Deleting user
echo "INFO: Deleting user $client_username..."
sleep 2
sudo userdel -rf $client_username 2>/dev/null

echo "DONE"
